### PR TITLE
Python

### PR DESCRIPTION
**Pull request by dzyanis**
roadmap

### CODE REVIEW

**Comment by horberlan** [comment]
how can i help in this repository?

**Comment by dzyanis** [comment]
> how can i help in this repository?

Hi! Sure! Do you know, I'm not so familiar with Python and probably the knowledge tree doesn't represent reality
roadmap

Could you please just simple review it.

**Comment by dzyanis** [comment]
@horberlan at least there is no Django and I think it's important to know this framework in any case. What do you think?

**Comment by daspartho** [comment]
a few improvements can be made in the data types section

**Pull request merged**
